# Generated by Django 4.1.5 on 2023-02-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0002_organizasyon_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mekan_Adi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mekan_adi', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Org_Tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_tur', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paket_Tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket_tur', models.TextField(max_length=200)),
            ],
        ),
    ]
