# Generated by Django 4.1.5 on 2023-02-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0003_mekan_adi_org_tur_paket_tur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mekan_adi',
            options={'verbose_name': 'Mekan Adı', 'verbose_name_plural': 'Mekan Adları'},
        ),
        migrations.AlterModelOptions(
            name='org_tur',
            options={'verbose_name': 'Organizasyon Türü', 'verbose_name_plural': 'Organizasyon Türleri'},
        ),
        migrations.AlterModelOptions(
            name='organizasyon',
            options={'verbose_name': 'Organizasyon', 'verbose_name_plural': 'Organizasyonlar'},
        ),
        migrations.AlterModelOptions(
            name='paket_tur',
            options={'verbose_name': 'Paket Türü', 'verbose_name_plural': 'Paket Türleri'},
        ),
    ]
