# Generated by Django 4.1.5 on 2023-02-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0004_alter_mekan_adi_options_alter_org_tur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sarkilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarki_adi', models.TextField(max_length=200, verbose_name='Şarkı Adı')),
            ],
            options={
                'verbose_name': 'Şarkı',
                'verbose_name_plural': 'Şarkılar',
            },
        ),
        migrations.AlterField(
            model_name='mekan_adi',
            name='mekan_adi',
            field=models.TextField(max_length=200, verbose_name='Mekan Adı'),
        ),
        migrations.AlterField(
            model_name='org_tur',
            name='org_tur',
            field=models.TextField(max_length=200, verbose_name='Organizasyon Türü'),
        ),
        migrations.AlterField(
            model_name='paket_tur',
            name='paket_tur',
            field=models.TextField(max_length=200, verbose_name='Paket Türü'),
        ),
    ]
