# Generated by Django 4.1.5 on 2023-02-20 23:18

from django.db import migrations, models
import fingo_etkinlik.models


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0006_sarkilar_oncelik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarkilar',
            name='oncelik',
            field=models.IntegerField(default=fingo_etkinlik.models.get_new_default, max_length=2000, verbose_name='Öncelik'),
        ),
    ]
