# Generated by Django 4.1.5 on 2023-02-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0009_alter_organizasyon_org_otel_adi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizasyon',
            name='sarkilar',
            field=models.ManyToManyField(to='fingo_etkinlik.sarkilar'),
        ),
    ]
