# Generated by Django 4.1.5 on 2023-02-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0010_organizasyon_sarkilar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizasyon',
            name='sarkilar',
        ),
    ]
