# Generated by Django 4.1.5 on 2023-02-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0011_remove_organizasyon_sarkilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModelAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
