# Generated by Django 4.1.5 on 2023-02-23 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0014_remove_organizasyon_eklenme_tarih_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizasyon',
            name='org_tarih',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
