# Generated by Django 4.1.5 on 2023-08-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0015_organizasyon_org_tarih'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sozlesme_Durumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sozlesme_yapildi', models.TextField(max_length=5, verbose_name='Sözleşme Yapıldı?')),
            ],
            options={
                'verbose_name': 'Sözleşme Yapıldı?',
                'verbose_name_plural': 'Sözleşme Yapıldı?',
            },
        ),
        migrations.AlterField(
            model_name='organizasyon',
            name='sozlesme_yapildi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fingo_etkinlik.sozlesme_durumu'),
        ),
    ]
