# Generated by Django 4.1.5 on 2023-08-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0016_sozlesme_durumu_alter_organizasyon_sozlesme_yapildi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sarki_Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oncelik', models.IntegerField(verbose_name='Şarkı Kategorisi Önceliği')),
                ('kategori_adi', models.TextField(max_length=200, verbose_name='Şarkı Kategorisi')),
            ],
            options={
                'verbose_name': 'Şarkı Kategorisi',
                'verbose_name_plural': 'Şarkı Kategorileri',
            },
        ),
        migrations.AddField(
            model_name='sarkilar',
            name='kategori',
            field=models.ManyToManyField(to='fingo_etkinlik.sarki_kategori'),
        ),
    ]
