# Generated by Django 4.1.5 on 2023-08-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0017_sarki_kategori_sarkilar_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sarkilar',
            name='kategori',
        ),
        migrations.AlterField(
            model_name='organizasyon',
            name='org_tarih',
            field=models.DateField(),
        ),
    ]
