# Generated by Django 4.1.5 on 2023-10-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_etkinlik', '0018_remove_sarkilar_kategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizasyon',
            name='sarkilar',
        ),
        migrations.AddField(
            model_name='organizasyon',
            name='sarkilar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fingo_etkinlik.sarkilar'),
        ),
    ]
